### ISSUE TITLE
Account id as an input

### ISSUE THREAD

**Issue by shahriartwxa** [xapo/xapo-security-checks-composite-action#1]
https://github.com/xapo/xapo-security-checks-composite-action/blob/ce6191d3b5deed968fc650cd7de73fd76f3a7c6b/action.yml#L103

**Comment by fabiopires** [comment]
Nice one. Hosts, passwords, repository names or anything that could be seen has "sensitive" is now passed as input.

I'll leave this repo public for now until https://github.com/github/roadmap/issues/74 is closed.

Cheers
